"""create tables

Revision ID: 9b9a25008bf0
Revises:
Create Date: 2025-09-24 06:34:05.376893

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b9a25008bf0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_price", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column(
            "status", sa.Enum("running", "ended", name="lotstatusenum"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lots_id"), "lots", ["id"], unique=False)
    op.create_table(
        "bids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bidder", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lot_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bids_id"), "bids", ["id"], unique=False)
    op.create_index(op.f("ix_bids_lot_id"), "bids", ["lot_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bids_lot_id"), table_name="bids")
    op.drop_index(op.f("ix_bids_id"), table_name="bids")
    op.drop_table("bids")
    op.drop_index(op.f("ix_lots_id"), table_name="lots")
    op.drop_table("lots")
    # ### end Alembic commands ###
